/**
 * DSA Roadmap dataset — 30 levels, 3 core problems each.
 * Each problem: id, title, prompt, example input/output, and starter code.
 * Exposed as a global (classic script) so the app works even when opened via file://.
 */
window.LEVELS = [
  // ---------------- LEVELS 1–20: FOUNDATION TO ADVANCED ----------------
  {
    id: 1, name: "Math Basics", tier: "Foundation", difficulty: "Beginner",
    problems: [
      { id: "1-1", title: "Prime Number Check",
        prompt: "Given an integer n, return true if n is a prime number, otherwise false.",
        input: "n = 7", output: "true",
        starter: "function isPrime(n) {\n  // your code here\n}\n\nconsole.log(isPrime(7));" },
      { id: "1-2", title: "Armstrong Number",
        prompt: "An Armstrong number equals the sum of its own digits each raised to the power of the number of digits. Return true/false.",
        input: "n = 153", output: "true  (1^3 + 5^3 + 3^3 = 153)",
        starter: "function isArmstrong(n) {\n  // your code here\n}\n\nconsole.log(isArmstrong(153));" },
      { id: "1-3", title: "Factorial of a Number",
        prompt: "Return the factorial of a non-negative integer n (n!).",
        input: "n = 5", output: "120",
        starter: "function factorial(n) {\n  // your code here\n}\n\nconsole.log(factorial(5));" },
    ],
  },
  {
    id: 2, name: "Arrays", tier: "Foundation", difficulty: "Beginner",
    problems: [
      { id: "2-1", title: "Two Sum",
        prompt: "Return the indices of the two numbers in nums that add up to target.",
        input: "nums = [2,7,11,15], target = 9", output: "[0, 1]",
        starter: "function twoSum(nums, target) {\n  // your code here\n}\n\nconsole.log(twoSum([2,7,11,15], 9));" },
      { id: "2-2", title: "Best Time to Buy and Sell Stock",
        prompt: "Given daily prices, return the max profit from one buy then one later sell.",
        input: "prices = [7,1,5,3,6,4]", output: "5  (buy at 1, sell at 6)",
        starter: "function maxProfit(prices) {\n  // your code here\n}\n\nconsole.log(maxProfit([7,1,5,3,6,4]));" },
      { id: "2-3", title: "Remove Duplicates from Sorted Array",
        prompt: "Remove duplicates in-place from a sorted array and return the new length.",
        input: "nums = [1,1,2]", output: "2  (nums becomes [1,2,...])",
        starter: "function removeDuplicates(nums) {\n  // your code here\n}\n\nconsole.log(removeDuplicates([1,1,2]));" },
    ],
  },
  {
    id: 3, name: "Strings", tier: "Foundation", difficulty: "Beginner",
    problems: [
      { id: "3-1", title: "Valid Anagram",
        prompt: "Return true if t is an anagram of s.",
        input: 's = "anagram", t = "nagaram"', output: "true",
        starter: 'function isAnagram(s, t) {\n  // your code here\n}\n\nconsole.log(isAnagram("anagram", "nagaram"));' },
      { id: "3-2", title: "Valid Palindrome",
        prompt: "Return true if the string reads the same forward and backward (ignore non-alphanumerics, case-insensitive).",
        input: 's = "A man, a plan, a canal: Panama"', output: "true",
        starter: 'function isPalindrome(s) {\n  // your code here\n}\n\nconsole.log(isPalindrome("A man, a plan, a canal: Panama"));' },
      { id: "3-3", title: "Longest Common Prefix",
        prompt: "Return the longest common prefix among an array of strings.",
        input: 'strs = ["flower","flow","flight"]', output: '"fl"',
        starter: 'function longestCommonPrefix(strs) {\n  // your code here\n}\n\nconsole.log(longestCommonPrefix(["flower","flow","flight"]));' },
    ],
  },
  {
    id: 4, name: "Hashing", tier: "Foundation", difficulty: "Beginner",
    problems: [
      { id: "4-1", title: "Contains Duplicate",
        prompt: "Return true if any value appears at least twice in the array.",
        input: "nums = [1,2,3,1]", output: "true",
        starter: "function containsDuplicate(nums) {\n  // your code here\n}\n\nconsole.log(containsDuplicate([1,2,3,1]));" },
      { id: "4-2", title: "Group Anagrams",
        prompt: "Group the strings that are anagrams of each other.",
        input: 'strs = ["eat","tea","tan","ate","nat","bat"]', output: '[["eat","tea","ate"],["tan","nat"],["bat"]]',
        starter: 'function groupAnagrams(strs) {\n  // your code here\n}\n\nconsole.log(groupAnagrams(["eat","tea","tan","ate","nat","bat"]));' },
      { id: "4-3", title: "Top K Frequent Elements",
        prompt: "Return the k most frequent elements.",
        input: "nums = [1,1,1,2,2,3], k = 2", output: "[1, 2]",
        starter: "function topKFrequent(nums, k) {\n  // your code here\n}\n\nconsole.log(topKFrequent([1,1,1,2,2,3], 2));" },
    ],
  },
  {
    id: 5, name: "Stack & Queue", tier: "Foundation", difficulty: "Beginner",
    problems: [
      { id: "5-1", title: "Valid Parentheses",
        prompt: "Return true if every open bracket is closed by the same type in the correct order.",
        input: 's = "{[]}"', output: "true",
        starter: 'function isValid(s) {\n  // your code here\n}\n\nconsole.log(isValid("{[]}"));' },
      { id: "5-2", title: "Min Stack",
        prompt: "Design a stack supporting push, pop, top, and retrieving the minimum in O(1).",
        input: "push(-2), push(0), push(-3), getMin()", output: "-3",
        starter: "class MinStack {\n  constructor() {\n    // your code here\n  }\n  push(x) {}\n  pop() {}\n  top() {}\n  getMin() {}\n}\n\nconst s = new MinStack();\ns.push(-2); s.push(0); s.push(-3);\nconsole.log(s.getMin());" },
      { id: "5-3", title: "Implement Queue using Stacks",
        prompt: "Implement a FIFO queue using only two stacks.",
        input: "push(1), push(2), peek(), pop()", output: "1, 1",
        starter: "class MyQueue {\n  constructor() {\n    // your code here\n  }\n  push(x) {}\n  pop() {}\n  peek() {}\n  empty() {}\n}\n\nconst q = new MyQueue();\nq.push(1); q.push(2);\nconsole.log(q.peek(), q.pop());" },
      { id: "5-4", title: "Implement a Stack",
        prompt: "Build a Stack (LIFO) from scratch with push(x), pop(), peek(), isEmpty(), and size(). pop/peek on an empty stack should return undefined.",
        input: "push(1); push(2); push(3); pop(); peek(); size()", output: "pop -> 3, peek -> 2, size -> 2",
        starter: "class Stack {\n  constructor() {\n    // your code here\n  }\n  push(x) {}\n  pop() {}\n  peek() {}\n  isEmpty() {}\n  size() {}\n}\n\nconst s = new Stack();\ns.push(1); s.push(2); s.push(3);\nconsole.log(s.pop());   // 3\nconsole.log(s.peek());  // 2\nconsole.log(s.size());  // 2" },
      { id: "5-5", title: "Implement a Queue",
        prompt: "Build a Queue (FIFO) from scratch with enqueue(x), dequeue(), front(), isEmpty(), and size(). dequeue/front on an empty queue should return undefined.",
        input: "enqueue(1); enqueue(2); enqueue(3); dequeue(); front(); size()", output: "dequeue -> 1, front -> 2, size -> 2",
        starter: "class Queue {\n  constructor() {\n    // your code here\n  }\n  enqueue(x) {}\n  dequeue() {}\n  front() {}\n  isEmpty() {}\n  size() {}\n}\n\nconst q = new Queue();\nq.enqueue(1); q.enqueue(2); q.enqueue(3);\nconsole.log(q.dequeue()); // 1\nconsole.log(q.front());   // 2\nconsole.log(q.size());    // 2" },
      { id: "5-6", title: "Implement a Deque",
        prompt: "Build a double-ended queue (Deque) with addFront(x), addRear(x), removeFront(), removeRear(), and size().",
        input: "addRear(1); addFront(2); removeRear(); removeFront()", output: "removeRear -> 1, removeFront -> 2",
        starter: "class Deque {\n  constructor() {\n    // your code here\n  }\n  addFront(x) {}\n  addRear(x) {}\n  removeFront() {}\n  removeRear() {}\n  size() {}\n}\n\nconst d = new Deque();\nd.addRear(1); d.addFront(2);\nconsole.log(d.removeRear());  // 1\nconsole.log(d.removeFront()); // 2" },
    ],
  },
  {
    id: 6, name: "Linked List", tier: "Advanced", difficulty: "Easy–Intermediate",
    problems: [
      { id: "6-1", title: "Reverse Linked List",
        prompt: "Reverse a singly linked list and return the new head.",
        input: "1 -> 2 -> 3 -> 4 -> 5", output: "5 -> 4 -> 3 -> 2 -> 1",
        starter: "function ListNode(val, next = null) { this.val = val; this.next = next; }\n\nfunction reverseList(head) {\n  // your code here\n}\n\n// build 1->2->3\nconst head = new ListNode(1, new ListNode(2, new ListNode(3)));\nlet r = reverseList(head);\nwhile (r) { console.log(r.val); r = r.next; }" },
      { id: "6-2", title: "Middle of the Linked List",
        prompt: "Return the middle node of a linked list (second middle if even length).",
        input: "1 -> 2 -> 3 -> 4 -> 5", output: "3 -> 4 -> 5",
        starter: "function ListNode(val, next = null) { this.val = val; this.next = next; }\n\nfunction middleNode(head) {\n  // your code here\n}\n\nconst head = new ListNode(1, new ListNode(2, new ListNode(3, new ListNode(4, new ListNode(5)))));\nconsole.log(middleNode(head).val);" },
      { id: "6-3", title: "Linked List Cycle",
        prompt: "Return true if the linked list has a cycle.",
        input: "3 -> 2 -> 0 -> -4 -> (back to 2)", output: "true",
        starter: "function ListNode(val, next = null) { this.val = val; this.next = next; }\n\nfunction hasCycle(head) {\n  // your code here\n}\n\nconst a = new ListNode(3), b = new ListNode(2), c = new ListNode(0), d = new ListNode(-4);\na.next = b; b.next = c; c.next = d; d.next = b;\nconsole.log(hasCycle(a));" },
      { id: "6-4", title: "Implement a Singly Linked List",
        prompt: "Build a singly linked list class with append(x), prepend(x), toArray(), and size(). append adds to the tail, prepend adds to the head.",
        input: "append(1); append(2); prepend(0); toArray()", output: "[0, 1, 2]",
        starter: "class LinkedList {\n  constructor() {\n    // your code here\n  }\n  append(x) {}\n  prepend(x) {}\n  toArray() {}\n  size() {}\n}\n\nconst list = new LinkedList();\nlist.append(1); list.append(2); list.prepend(0);\nconsole.log(list.toArray()); // [0, 1, 2]" },
      { id: "6-5", title: "Doubly Linked List",
        prompt: "Build a doubly linked list with addFirst(x), addLast(x), toArray() (head→tail) and toArrayReverse() (tail→head). Each node links both ways.",
        input: "addLast(1); addLast(2); addFirst(0); toArray(); toArrayReverse()", output: "[0,1,2] and [2,1,0]",
        starter: "class DoublyLinkedList {\n  constructor() {\n    // your code here\n  }\n  addFirst(x) {}\n  addLast(x) {}\n  toArray() {}\n  toArrayReverse() {}\n}\n\nconst d = new DoublyLinkedList();\nd.addLast(1); d.addLast(2); d.addFirst(0);\nconsole.log(d.toArray());        // [0,1,2]\nconsole.log(d.toArrayReverse()); // [2,1,0]" },
    ],
  },
  {
    id: 7, name: "Recursion", tier: "Advanced", difficulty: "Easy–Intermediate",
    problems: [
      { id: "7-1", title: "Fibonacci Number",
        prompt: "Return the nth Fibonacci number (F(0)=0, F(1)=1).",
        input: "n = 6", output: "8",
        starter: "function fib(n) {\n  // your code here\n}\n\nconsole.log(fib(6));" },
      { id: "7-2", title: "Generate Parentheses",
        prompt: "Generate all combinations of n pairs of well-formed parentheses.",
        input: "n = 3", output: '["((()))","(()())","(())()","()(())","()()()"]',
        starter: "function generateParenthesis(n) {\n  // your code here\n}\n\nconsole.log(generateParenthesis(3));" },
      { id: "7-3", title: "Letter Combinations of a Phone Number",
        prompt: "Return all letter combinations the digit string could represent (phone keypad).",
        input: 'digits = "23"', output: '["ad","ae","af","bd","be","bf","cd","ce","cf"]',
        starter: 'function letterCombinations(digits) {\n  // your code here\n}\n\nconsole.log(letterCombinations("23"));' },
    ],
  },
  {
    id: 8, name: "Binary Search", tier: "Advanced", difficulty: "Easy–Intermediate",
    problems: [
      { id: "8-1", title: "Binary Search",
        prompt: "Return the index of target in a sorted array, or -1 if not present.",
        input: "nums = [-1,0,3,5,9,12], target = 9", output: "4",
        starter: "function search(nums, target) {\n  // your code here\n}\n\nconsole.log(search([-1,0,3,5,9,12], 9));" },
      { id: "8-2", title: "Search in Rotated Sorted Array",
        prompt: "Search target in a rotated sorted array in O(log n). Return index or -1.",
        input: "nums = [4,5,6,7,0,1,2], target = 0", output: "4",
        starter: "function search(nums, target) {\n  // your code here\n}\n\nconsole.log(search([4,5,6,7,0,1,2], 0));" },
      { id: "8-3", title: "Find Peak Element",
        prompt: "Return the index of any peak element (greater than its neighbors).",
        input: "nums = [1,2,3,1]", output: "2",
        starter: "function findPeakElement(nums) {\n  // your code here\n}\n\nconsole.log(findPeakElement([1,2,3,1]));" },
    ],
  },
  {
    id: 9, name: "Sorting", tier: "Advanced", difficulty: "Easy–Intermediate",
    problems: [
      { id: "9-1", title: "Sort Colors",
        prompt: "Sort an array of 0s, 1s, and 2s in-place (Dutch National Flag).",
        input: "nums = [2,0,2,1,1,0]", output: "[0,0,1,1,2,2]",
        starter: "function sortColors(nums) {\n  // your code here\n}\n\nconst n = [2,0,2,1,1,0];\nsortColors(n);\nconsole.log(n);" },
      { id: "9-2", title: "Merge Intervals",
        prompt: "Merge all overlapping intervals.",
        input: "intervals = [[1,3],[2,6],[8,10],[15,18]]", output: "[[1,6],[8,10],[15,18]]",
        starter: "function merge(intervals) {\n  // your code here\n}\n\nconsole.log(merge([[1,3],[2,6],[8,10],[15,18]]));" },
      { id: "9-3", title: "Kth Largest Element in an Array",
        prompt: "Return the kth largest element in the array.",
        input: "nums = [3,2,1,5,6,4], k = 2", output: "5",
        starter: "function findKthLargest(nums, k) {\n  // your code here\n}\n\nconsole.log(findKthLargest([3,2,1,5,6,4], 2));" },
      { id: "9-4", title: "Bubble Sort",
        prompt: "Implement bubble sort. Return a NEW array sorted in ascending order (repeatedly swap adjacent out-of-order elements).",
        input: "arr = [5,2,9,1,5,6]", output: "[1,2,5,5,6,9]",
        starter: "function bubbleSort(arr) {\n  // your code here\n}\n\nconsole.log(bubbleSort([5,2,9,1,5,6]));" },
      { id: "9-5", title: "Insertion Sort",
        prompt: "Implement insertion sort. Return the array sorted ascending by inserting each element into its correct position among the sorted prefix.",
        input: "arr = [5,2,9,1]", output: "[1,2,5,9]",
        starter: "function insertionSort(arr) {\n  // your code here\n}\n\nconsole.log(insertionSort([5,2,9,1]));" },
      { id: "9-6", title: "Selection Sort",
        prompt: "Implement selection sort. Return the array sorted ascending by repeatedly selecting the minimum of the remaining part.",
        input: "arr = [64,25,12,22,11]", output: "[11,12,22,25,64]",
        starter: "function selectionSort(arr) {\n  // your code here\n}\n\nconsole.log(selectionSort([64,25,12,22,11]));" },
      { id: "9-7", title: "Merge Sort",
        prompt: "Implement merge sort (divide & conquer). Return a new array sorted ascending. Time: O(n log n).",
        input: "arr = [38,27,43,3,9,82,10]", output: "[3,9,10,27,38,43,82]",
        starter: "function mergeSort(arr) {\n  // your code here\n}\n\nconsole.log(mergeSort([38,27,43,3,9,82,10]));" },
      { id: "9-8", title: "Quick Sort",
        prompt: "Implement quick sort (pick a pivot, partition, recurse). Return the array sorted ascending. Avg time: O(n log n).",
        input: "arr = [10,7,8,9,1,5]", output: "[1,5,7,8,9,10]",
        starter: "function quickSort(arr) {\n  // your code here\n}\n\nconsole.log(quickSort([10,7,8,9,1,5]));" },
      { id: "9-9", title: "Radix Sort",
        prompt: "Implement radix sort for non-negative integers (sort digit by digit using counting sort). Return the array sorted ascending.",
        input: "arr = [170,45,75,90,802,24,2,66]", output: "[2,24,45,66,75,90,170,802]",
        starter: "function radixSort(arr) {\n  // your code here\n}\n\nconsole.log(radixSort([170,45,75,90,802,24,2,66]));" },
    ],
  },
  {
    id: 10, name: "Two Pointers", tier: "Advanced", difficulty: "Easy–Intermediate",
    problems: [
      { id: "10-1", title: "Two Sum II (Sorted Input)",
        prompt: "Given a 1-indexed sorted array, return the two indices that add to target.",
        input: "numbers = [2,7,11,15], target = 9", output: "[1, 2]",
        starter: "function twoSum(numbers, target) {\n  // your code here\n}\n\nconsole.log(twoSum([2,7,11,15], 9));" },
      { id: "10-2", title: "3Sum",
        prompt: "Return all unique triplets that sum to zero.",
        input: "nums = [-1,0,1,2,-1,-4]", output: "[[-1,-1,2],[-1,0,1]]",
        starter: "function threeSum(nums) {\n  // your code here\n}\n\nconsole.log(threeSum([-1,0,1,2,-1,-4]));" },
      { id: "10-3", title: "Container With Most Water",
        prompt: "Return the maximum water area between two lines.",
        input: "height = [1,8,6,2,5,4,8,3,7]", output: "49",
        starter: "function maxArea(height) {\n  // your code here\n}\n\nconsole.log(maxArea([1,8,6,2,5,4,8,3,7]));" },
    ],
  },
  {
    id: 11, name: "Sliding Window", tier: "Advanced", difficulty: "Intermediate",
    problems: [
      { id: "11-1", title: "Longest Substring Without Repeating Characters",
        prompt: "Return the length of the longest substring without repeating characters.",
        input: 's = "abcabcbb"', output: "3  (\"abc\")",
        starter: 'function lengthOfLongestSubstring(s) {\n  // your code here\n}\n\nconsole.log(lengthOfLongestSubstring("abcabcbb"));' },
      { id: "11-2", title: "Maximum Average Subarray I",
        prompt: "Return the maximum average of any contiguous subarray of length k.",
        input: "nums = [1,12,-5,-6,50,3], k = 4", output: "12.75",
        starter: "function findMaxAverage(nums, k) {\n  // your code here\n}\n\nconsole.log(findMaxAverage([1,12,-5,-6,50,3], 4));" },
      { id: "11-3", title: "Minimum Size Subarray Sum",
        prompt: "Return the minimal length of a contiguous subarray whose sum ≥ target (0 if none).",
        input: "target = 7, nums = [2,3,1,2,4,3]", output: "2  ([4,3])",
        starter: "function minSubArrayLen(target, nums) {\n  // your code here\n}\n\nconsole.log(minSubArrayLen(7, [2,3,1,2,4,3]));" },
    ],
  },
  {
    id: 12, name: "Prefix Sum", tier: "Advanced", difficulty: "Intermediate",
    problems: [
      { id: "12-1", title: "Range Sum Query (Immutable)",
        prompt: "Preprocess so sumRange(i, j) returns the sum of nums[i..j] in O(1).",
        input: "nums = [-2,0,3,-5,2,-1]; sumRange(0,2)", output: "1",
        starter: "class NumArray {\n  constructor(nums) {\n    // your code here\n  }\n  sumRange(i, j) {}\n}\n\nconst na = new NumArray([-2,0,3,-5,2,-1]);\nconsole.log(na.sumRange(0,2));" },
      { id: "12-2", title: "Subarray Sum Equals K",
        prompt: "Return the number of contiguous subarrays that sum to k.",
        input: "nums = [1,1,1], k = 2", output: "2",
        starter: "function subarraySum(nums, k) {\n  // your code here\n}\n\nconsole.log(subarraySum([1,1,1], 2));" },
      { id: "12-3", title: "Product of Array Except Self",
        prompt: "Return an array where output[i] is the product of all elements except nums[i] (no division).",
        input: "nums = [1,2,3,4]", output: "[24,12,8,6]",
        starter: "function productExceptSelf(nums) {\n  // your code here\n}\n\nconsole.log(productExceptSelf([1,2,3,4]));" },
    ],
  },
  {
    id: 13, name: "Intervals", tier: "Advanced", difficulty: "Intermediate",
    problems: [
      { id: "13-1", title: "Insert Interval",
        prompt: "Insert a new interval into a sorted, non-overlapping list and merge if needed.",
        input: "intervals = [[1,3],[6,9]], newInterval = [2,5]", output: "[[1,5],[6,9]]",
        starter: "function insert(intervals, newInterval) {\n  // your code here\n}\n\nconsole.log(insert([[1,3],[6,9]], [2,5]));" },
      { id: "13-2", title: "Non-overlapping Intervals",
        prompt: "Return the minimum number of intervals to remove so the rest don't overlap.",
        input: "intervals = [[1,2],[2,3],[3,4],[1,3]]", output: "1",
        starter: "function eraseOverlapIntervals(intervals) {\n  // your code here\n}\n\nconsole.log(eraseOverlapIntervals([[1,2],[2,3],[3,4],[1,3]]));" },
      { id: "13-3", title: "Meeting Rooms II",
        prompt: "Return the minimum number of conference rooms required.",
        input: "intervals = [[0,30],[5,10],[15,20]]", output: "2",
        starter: "function minMeetingRooms(intervals) {\n  // your code here\n}\n\nconsole.log(minMeetingRooms([[0,30],[5,10],[15,20]]));" },
    ],
  },
  {
    id: 14, name: "Binary Trees", tier: "Advanced", difficulty: "Intermediate",
    problems: [
      { id: "14-1", title: "Maximum Depth of Binary Tree",
        prompt: "Return the maximum depth (number of nodes along the longest root-to-leaf path).",
        input: "root = [3,9,20,null,null,15,7]", output: "3",
        starter: "function TreeNode(val, left = null, right = null) { this.val = val; this.left = left; this.right = right; }\n\nfunction maxDepth(root) {\n  // your code here\n}\n\nconst root = new TreeNode(3, new TreeNode(9), new TreeNode(20, new TreeNode(15), new TreeNode(7)));\nconsole.log(maxDepth(root));" },
      { id: "14-2", title: "Binary Tree Level Order Traversal",
        prompt: "Return the level-order (BFS) traversal as an array of levels.",
        input: "root = [3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]",
        starter: "function TreeNode(val, left = null, right = null) { this.val = val; this.left = left; this.right = right; }\n\nfunction levelOrder(root) {\n  // your code here\n}\n\nconst root = new TreeNode(3, new TreeNode(9), new TreeNode(20, new TreeNode(15), new TreeNode(7)));\nconsole.log(levelOrder(root));" },
      { id: "14-3", title: "Invert Binary Tree",
        prompt: "Invert (mirror) a binary tree and return the root.",
        input: "root = [4,2,7,1,3,6,9]", output: "[4,7,2,9,6,3,1]",
        starter: "function TreeNode(val, left = null, right = null) { this.val = val; this.left = left; this.right = right; }\n\nfunction invertTree(root) {\n  // your code here\n}\n\nconst root = new TreeNode(4, new TreeNode(2), new TreeNode(7));\nconsole.log(invertTree(root));" },
    ],
  },
  {
    id: 15, name: "Binary Search Tree", tier: "Advanced", difficulty: "Intermediate",
    problems: [
      { id: "15-1", title: "Validate BST",
        prompt: "Return true if a binary tree is a valid binary search tree.",
        input: "root = [2,1,3]", output: "true",
        starter: "function TreeNode(val, left = null, right = null) { this.val = val; this.left = left; this.right = right; }\n\nfunction isValidBST(root) {\n  // your code here\n}\n\nconst root = new TreeNode(2, new TreeNode(1), new TreeNode(3));\nconsole.log(isValidBST(root));" },
      { id: "15-2", title: "Lowest Common Ancestor in BST",
        prompt: "Return the lowest common ancestor of two nodes in a BST.",
        input: "root = [6,2,8,...], p = 2, q = 8", output: "6",
        starter: "function TreeNode(val, left = null, right = null) { this.val = val; this.left = left; this.right = right; }\n\nfunction lowestCommonAncestor(root, p, q) {\n  // your code here\n}\n\nconst root = new TreeNode(6, new TreeNode(2), new TreeNode(8));\nconsole.log(lowestCommonAncestor(root, root.left, root.right).val);" },
      { id: "15-3", title: "Kth Smallest Element in a BST",
        prompt: "Return the kth smallest value in a BST.",
        input: "root = [3,1,4,null,2], k = 1", output: "1",
        starter: "function TreeNode(val, left = null, right = null) { this.val = val; this.left = left; this.right = right; }\n\nfunction kthSmallest(root, k) {\n  // your code here\n}\n\nconst root = new TreeNode(3, new TreeNode(1, null, new TreeNode(2)), new TreeNode(4));\nconsole.log(kthSmallest(root, 1));" },
      { id: "15-4", title: "Implement a BST",
        prompt: "Build a Binary Search Tree with insert(x), search(x) (true/false) and inorder() (returns values in ascending order). Duplicates may be ignored.",
        input: "insert 5,3,7,2,4; search(4); inorder()", output: "search → true, inorder → [2,3,4,5,7]",
        starter: "class BST {\n  constructor() {\n    // your code here\n  }\n  insert(x) {}\n  search(x) {}\n  inorder() {}\n}\n\nconst t = new BST();\n[5,3,7,2,4].forEach(v => t.insert(v));\nconsole.log(t.search(4));   // true\nconsole.log(t.inorder());   // [2,3,4,5,7]" },
    ],
  },
  {
    id: 16, name: "Heap / Priority Queue", tier: "Advanced", difficulty: "Intermediate–Advanced",
    problems: [
      { id: "16-1", title: "K Closest Points to Origin",
        prompt: "Return the k points closest to the origin (0,0).",
        input: "points = [[1,3],[-2,2]], k = 1", output: "[[-2,2]]",
        starter: "function kClosest(points, k) {\n  // your code here\n}\n\nconsole.log(kClosest([[1,3],[-2,2]], 1));" },
      { id: "16-2", title: "Last Stone Weight",
        prompt: "Smash the two heaviest stones repeatedly; return the weight of the last remaining stone (or 0).",
        input: "stones = [2,7,4,1,8,1]", output: "1",
        starter: "function lastStoneWeight(stones) {\n  // your code here\n}\n\nconsole.log(lastStoneWeight([2,7,4,1,8,1]));" },
      { id: "16-3", title: "Find Median from Data Stream",
        prompt: "Design a structure that adds numbers and returns the running median.",
        input: "addNum(1), addNum(2), findMedian(), addNum(3), findMedian()", output: "1.5, 2",
        starter: "class MedianFinder {\n  constructor() {\n    // your code here\n  }\n  addNum(num) {}\n  findMedian() {}\n}\n\nconst mf = new MedianFinder();\nmf.addNum(1); mf.addNum(2);\nconsole.log(mf.findMedian());\nmf.addNum(3);\nconsole.log(mf.findMedian());" },
    ],
  },
  {
    id: 17, name: "Trie", tier: "Advanced", difficulty: "Intermediate–Advanced",
    problems: [
      { id: "17-1", title: "Implement Trie (Prefix Tree)",
        prompt: "Implement a trie with insert, search, and startsWith.",
        input: 'insert("apple"), search("apple"), startsWith("app")', output: "true, true",
        starter: 'class Trie {\n  constructor() {\n    // your code here\n  }\n  insert(word) {}\n  search(word) {}\n  startsWith(prefix) {}\n}\n\nconst t = new Trie();\nt.insert("apple");\nconsole.log(t.search("apple"), t.startsWith("app"));' },
      { id: "17-2", title: "Add and Search Word (with '.')",
        prompt: "Design a dictionary where search supports '.' as a wildcard matching any letter.",
        input: 'addWord("bad"), search("b.d")', output: "true",
        starter: 'class WordDictionary {\n  constructor() {\n    // your code here\n  }\n  addWord(word) {}\n  search(word) {}\n}\n\nconst d = new WordDictionary();\nd.addWord("bad");\nconsole.log(d.search("b.d"));' },
      { id: "17-3", title: "Replace Words",
        prompt: "Replace each word in the sentence with the shortest root from the dictionary that is a prefix of it.",
        input: 'dict = ["cat","bat","rat"], "the cattle was rattled by the battery"', output: '"the cat was rat by the bat"',
        starter: 'function replaceWords(dictionary, sentence) {\n  // your code here\n}\n\nconsole.log(replaceWords(["cat","bat","rat"], "the cattle was rattled by the battery"));' },
    ],
  },
  {
    id: 18, name: "Union Find (DSU)", tier: "Advanced", difficulty: "Intermediate–Advanced",
    problems: [
      { id: "18-1", title: "Number of Provinces",
        prompt: "Given an adjacency matrix of cities, return the number of connected provinces.",
        input: "isConnected = [[1,1,0],[1,1,0],[0,0,1]]", output: "2",
        starter: "function findCircleNum(isConnected) {\n  // your code here\n}\n\nconsole.log(findCircleNum([[1,1,0],[1,1,0],[0,0,1]]));" },
      { id: "18-2", title: "Redundant Connection",
        prompt: "Return the edge that can be removed so the graph becomes a tree.",
        input: "edges = [[1,2],[1,3],[2,3]]", output: "[2,3]",
        starter: "function findRedundantConnection(edges) {\n  // your code here\n}\n\nconsole.log(findRedundantConnection([[1,2],[1,3],[2,3]]));" },
      { id: "18-3", title: "Accounts Merge",
        prompt: "Merge accounts that share any email; return merged accounts with sorted emails.",
        input: 'accounts = [["John","a@x","b@x"],["John","b@x","c@x"]]', output: '[["John","a@x","b@x","c@x"]]',
        starter: 'function accountsMerge(accounts) {\n  // your code here\n}\n\nconsole.log(accountsMerge([["John","a@x","b@x"],["John","b@x","c@x"]]));' },
    ],
  },
  {
    id: 19, name: "Graph Traversal", tier: "Advanced", difficulty: "Intermediate–Advanced",
    problems: [
      { id: "19-1", title: "Number of Islands",
        prompt: "Count the number of islands ('1' = land) in a grid.",
        input: 'grid = [["1","1","0"],["0","1","0"],["0","0","1"]]', output: "2",
        starter: 'function numIslands(grid) {\n  // your code here\n}\n\nconsole.log(numIslands([["1","1","0"],["0","1","0"],["0","0","1"]]));' },
      { id: "19-2", title: "Clone Graph",
        prompt: "Return a deep copy of a connected undirected graph.",
        input: "adjList = [[2,4],[1,3],[2,4],[1,3]]", output: "deep-cloned graph",
        starter: "function Node(val, neighbors = []) { this.val = val; this.neighbors = neighbors; }\n\nfunction cloneGraph(node) {\n  // your code here\n}\n\nconst a = new Node(1), b = new Node(2);\na.neighbors = [b]; b.neighbors = [a];\nconsole.log(cloneGraph(a).val);" },
      { id: "19-3", title: "Flood Fill",
        prompt: "Perform a flood fill from (sr, sc) with the new color.",
        input: "image = [[1,1,1],[1,1,0],[1,0,1]], sr=1, sc=1, color=2", output: "[[2,2,2],[2,2,0],[2,0,1]]",
        starter: "function floodFill(image, sr, sc, color) {\n  // your code here\n}\n\nconsole.log(floodFill([[1,1,1],[1,1,0],[1,0,1]], 1, 1, 2));" },
      { id: "19-4", title: "Implement a Graph (BFS & DFS)",
        prompt: "Build an undirected Graph with addEdge(u, v). Implement bfs(start) and dfs(start) returning the visit order. Visit neighbours in the order edges were added.",
        input: "edges (1-2,1-3,2-4,3-4); bfs(1); dfs(1)", output: "bfs → [1,2,3,4], dfs → [1,2,4,3]",
        starter: "class Graph {\n  constructor() {\n    this.adj = new Map();\n  }\n  addEdge(u, v) {\n    // undirected: link both ways (keep insertion order)\n  }\n  bfs(start) {\n    // return array of nodes in BFS order\n  }\n  dfs(start) {\n    // return array of nodes in DFS order\n  }\n}\n\nconst g = new Graph();\ng.addEdge(1,2); g.addEdge(1,3); g.addEdge(2,4); g.addEdge(3,4);\nconsole.log(g.bfs(1)); // [1,2,3,4]\nconsole.log(g.dfs(1)); // [1,2,4,3]" },
    ],
  },
  {
    id: 20, name: "Topological Sort & Cycle", tier: "Advanced", difficulty: "Intermediate–Advanced",
    problems: [
      { id: "20-1", title: "Course Schedule",
        prompt: "Return true if you can finish all courses given prerequisites (no cycle).",
        input: "numCourses = 2, prerequisites = [[1,0]]", output: "true",
        starter: "function canFinish(numCourses, prerequisites) {\n  // your code here\n}\n\nconsole.log(canFinish(2, [[1,0]]));" },
      { id: "20-2", title: "Course Schedule II",
        prompt: "Return a valid ordering of courses to finish all of them (or [] if impossible).",
        input: "numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]", output: "[0,1,2,3]",
        starter: "function findOrder(numCourses, prerequisites) {\n  // your code here\n}\n\nconsole.log(findOrder(4, [[1,0],[2,0],[3,1],[3,2]]));" },
      { id: "20-3", title: "Alien Dictionary",
        prompt: "Given words sorted lexicographically in an alien language, return the character order.",
        input: 'words = ["wrt","wrf","er","ett","rftt"]', output: '"wertf"',
        starter: 'function alienOrder(words) {\n  // your code here\n}\n\nconsole.log(alienOrder(["wrt","wrf","er","ett","rftt"]));' },
    ],
  },

  // ---------------- LEVELS 21–30: MASTERY & TOP TIER ----------------
  {
    id: 21, name: "Shortest Paths", tier: "Mastery", difficulty: "Advanced",
    problems: [
      { id: "21-1", title: "Network Delay Time",
        prompt: "Return the time for all n nodes to receive a signal from node k (or -1).",
        input: "times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2", output: "2",
        starter: "function networkDelayTime(times, n, k) {\n  // your code here\n}\n\nconsole.log(networkDelayTime([[2,1,1],[2,3,1],[3,4,1]], 4, 2));" },
      { id: "21-2", title: "Cheapest Flights Within K Stops",
        prompt: "Find the cheapest price from src to dst with at most k stops (or -1).",
        input: "n=4, flights=[[0,1,100],[1,2,100],[2,3,100]], src=0, dst=3, k=1", output: "-1",
        starter: "function findCheapestPrice(n, flights, src, dst, k) {\n  // your code here\n}\n\nconsole.log(findCheapestPrice(4, [[0,1,100],[1,2,100],[2,3,100]], 0, 3, 1));" },
      { id: "21-3", title: "Path With Minimum Effort",
        prompt: "Minimize the maximum absolute height difference along a path from top-left to bottom-right.",
        input: "heights = [[1,2,2],[3,8,2],[5,3,5]]", output: "2",
        starter: "function minimumEffortPath(heights) {\n  // your code here\n}\n\nconsole.log(minimumEffortPath([[1,2,2],[3,8,2],[5,3,5]]));" },
    ],
  },
  {
    id: 22, name: "Minimum Spanning Tree", tier: "Mastery", difficulty: "Advanced",
    problems: [
      { id: "22-1", title: "Min Cost to Connect All Points",
        prompt: "Return the minimum cost to connect all points (Manhattan distance).",
        input: "points = [[0,0],[2,2],[3,10],[5,2],[7,0]]", output: "20",
        starter: "function minCostConnectPoints(points) {\n  // your code here\n}\n\nconsole.log(minCostConnectPoints([[0,0],[2,2],[3,10],[5,2],[7,0]]));" },
      { id: "22-2", title: "Connecting Cities With Minimum Cost",
        prompt: "Return the minimum cost to connect all n cities, or -1 if impossible.",
        input: "n = 3, connections = [[1,2,5],[1,3,6],[2,3,1]]", output: "6",
        starter: "function minimumCost(n, connections) {\n  // your code here\n}\n\nconsole.log(minimumCost(3, [[1,2,5],[1,3,6],[2,3,1]]));" },
      { id: "22-3", title: "Optimize Water Distribution in a Village",
        prompt: "Minimize cost to supply water via wells or pipes across n houses.",
        input: "n=3, wells=[1,2,2], pipes=[[1,2,1],[2,3,1]]", output: "3",
        starter: "function minCostToSupplyWater(n, wells, pipes) {\n  // your code here\n}\n\nconsole.log(minCostToSupplyWater(3, [1,2,2], [[1,2,1],[2,3,1]]));" },
    ],
  },
  {
    id: 23, name: "Greedy Algorithms", tier: "Mastery", difficulty: "Advanced",
    problems: [
      { id: "23-1", title: "Jump Game",
        prompt: "Return true if you can reach the last index (nums[i] = max jump length).",
        input: "nums = [2,3,1,1,4]", output: "true",
        starter: "function canJump(nums) {\n  // your code here\n}\n\nconsole.log(canJump([2,3,1,1,4]));" },
      { id: "23-2", title: "Gas Station",
        prompt: "Return the starting station index to complete the circuit once, or -1.",
        input: "gas = [1,2,3,4,5], cost = [3,4,5,1,2]", output: "3",
        starter: "function canCompleteCircuit(gas, cost) {\n  // your code here\n}\n\nconsole.log(canCompleteCircuit([1,2,3,4,5], [3,4,5,1,2]));" },
      { id: "23-3", title: "Task Scheduler",
        prompt: "Return the least time to finish all tasks with cooldown n between same tasks.",
        input: 'tasks = ["A","A","A","B","B","B"], n = 2', output: "8",
        starter: 'function leastInterval(tasks, n) {\n  // your code here\n}\n\nconsole.log(leastInterval(["A","A","A","B","B","B"], 2));' },
    ],
  },
  {
    id: 24, name: "Dynamic Programming I", tier: "Mastery", difficulty: "Advanced",
    problems: [
      { id: "24-1", title: "Climbing Stairs",
        prompt: "Return the number of distinct ways to climb n stairs (1 or 2 steps).",
        input: "n = 5", output: "8",
        starter: "function climbStairs(n) {\n  // your code here\n}\n\nconsole.log(climbStairs(5));" },
      { id: "24-2", title: "House Robber",
        prompt: "Return the max amount you can rob without robbing two adjacent houses.",
        input: "nums = [2,7,9,3,1]", output: "12",
        starter: "function rob(nums) {\n  // your code here\n}\n\nconsole.log(rob([2,7,9,3,1]));" },
      { id: "24-3", title: "Coin Change",
        prompt: "Return the fewest coins to make up amount, or -1 if impossible.",
        input: "coins = [1,2,5], amount = 11", output: "3  (5+5+1)",
        starter: "function coinChange(coins, amount) {\n  // your code here\n}\n\nconsole.log(coinChange([1,2,5], 11));" },
    ],
  },
  {
    id: 25, name: "Dynamic Programming II", tier: "Mastery", difficulty: "Advanced",
    problems: [
      { id: "25-1", title: "Longest Increasing Subsequence",
        prompt: "Return the length of the longest strictly increasing subsequence.",
        input: "nums = [10,9,2,5,3,7,101,18]", output: "4",
        starter: "function lengthOfLIS(nums) {\n  // your code here\n}\n\nconsole.log(lengthOfLIS([10,9,2,5,3,7,101,18]));" },
      { id: "25-2", title: "Longest Common Subsequence",
        prompt: "Return the length of the longest common subsequence of two strings.",
        input: 'text1 = "abcde", text2 = "ace"', output: "3  (\"ace\")",
        starter: 'function longestCommonSubsequence(text1, text2) {\n  // your code here\n}\n\nconsole.log(longestCommonSubsequence("abcde", "ace"));' },
      { id: "25-3", title: "0/1 Knapsack",
        prompt: "Maximize value within capacity W; each item used at most once.",
        input: "weights = [1,3,4,5], values = [1,4,5,7], W = 7", output: "9",
        starter: "function knapsack(weights, values, W) {\n  // your code here\n}\n\nconsole.log(knapsack([1,3,4,5], [1,4,5,7], 7));" },
    ],
  },
  {
    id: 26, name: "Backtracking", tier: "Mastery", difficulty: "Expert / Top-Tier",
    problems: [
      { id: "26-1", title: "Subsets",
        prompt: "Return all possible subsets (the power set) of distinct integers.",
        input: "nums = [1,2,3]", output: "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]",
        starter: "function subsets(nums) {\n  // your code here\n}\n\nconsole.log(subsets([1,2,3]));" },
      { id: "26-2", title: "N-Queens",
        prompt: "Return all distinct solutions to placing n non-attacking queens on an n×n board.",
        input: "n = 4", output: "2 solutions",
        starter: "function solveNQueens(n) {\n  // your code here\n}\n\nconsole.log(solveNQueens(4));" },
      { id: "26-3", title: "Sudoku Solver",
        prompt: "Fill an incomplete 9×9 Sudoku board in-place (assume one solution).",
        input: "board = 9×9 with '.' empties", output: "solved board",
        starter: "function solveSudoku(board) {\n  // your code here\n}\n\n// board is a 2D array of chars, '.' = empty\nconsole.log('implement solveSudoku');" },
    ],
  },
  {
    id: 27, name: "Bit Manipulation", tier: "Mastery", difficulty: "Expert / Top-Tier",
    problems: [
      { id: "27-1", title: "Single Number",
        prompt: "Every element appears twice except one — return that single one (O(1) space).",
        input: "nums = [4,1,2,1,2]", output: "4",
        starter: "function singleNumber(nums) {\n  // your code here\n}\n\nconsole.log(singleNumber([4,1,2,1,2]));" },
      { id: "27-2", title: "Number of 1 Bits",
        prompt: "Return the number of set bits (Hamming weight) of an integer.",
        input: "n = 11  (1011)", output: "3",
        starter: "function hammingWeight(n) {\n  // your code here\n}\n\nconsole.log(hammingWeight(11));" },
      { id: "27-3", title: "Swap Numbers (without temp)",
        prompt: "Swap two integers without using a temporary variable (use XOR).",
        input: "a = 5, b = 9", output: "a = 9, b = 5",
        starter: "function swap(a, b) {\n  // return [b, a] using bit tricks\n}\n\nconsole.log(swap(5, 9));" },
    ],
  },
  {
    id: 28, name: "Advanced Data Structures", tier: "Mastery", difficulty: "Expert / Top-Tier",
    problems: [
      { id: "28-1", title: "LRU Cache",
        prompt: "Design a Least Recently Used cache with O(1) get and put.",
        input: "capacity=2; put(1,1); put(2,2); get(1); put(3,3); get(2)", output: "1, -1",
        starter: "class LRUCache {\n  constructor(capacity) {\n    // your code here\n  }\n  get(key) {}\n  put(key, value) {}\n}\n\nconst c = new LRUCache(2);\nc.put(1,1); c.put(2,2);\nconsole.log(c.get(1));\nc.put(3,3);\nconsole.log(c.get(2));" },
      { id: "28-2", title: "Design Twitter",
        prompt: "Design Twitter: postTweet, getNewsFeed (10 most recent), follow, unfollow.",
        input: "postTweet(1,5); getNewsFeed(1)", output: "[5]",
        starter: "class Twitter {\n  constructor() {\n    // your code here\n  }\n  postTweet(userId, tweetId) {}\n  getNewsFeed(userId) {}\n  follow(followerId, followeeId) {}\n  unfollow(followerId, followeeId) {}\n}\n\nconst t = new Twitter();\nt.postTweet(1, 5);\nconsole.log(t.getNewsFeed(1));" },
      { id: "28-3", title: "Insert Delete GetRandom O(1)",
        prompt: "Design a set supporting insert, remove, and getRandom in average O(1).",
        input: "insert(1); insert(2); getRandom()", output: "1 or 2",
        starter: "class RandomizedSet {\n  constructor() {\n    // your code here\n  }\n  insert(val) {}\n  remove(val) {}\n  getRandom() {}\n}\n\nconst r = new RandomizedSet();\nr.insert(1); r.insert(2);\nconsole.log(r.getRandom());" },
    ],
  },
  {
    id: 29, name: "Advanced Graph Algorithms", tier: "Mastery", difficulty: "Expert / Top-Tier",
    problems: [
      { id: "29-1", title: "Strongly Connected Components (Kosaraju)",
        prompt: "Return the strongly connected components of a directed graph.",
        input: "n = 5, edges = [[0,1],[1,2],[2,0],[1,3],[3,4]]", output: "[[0,1,2],[3],[4]]",
        starter: "function kosarajuSCC(n, edges) {\n  // your code here\n}\n\nconsole.log(kosarajuSCC(5, [[0,1],[1,2],[2,0],[1,3],[3,4]]));" },
      { id: "29-2", title: "Articulation Points (Tarjan)",
        prompt: "Return all articulation points (cut vertices) in an undirected graph.",
        input: "n = 5, edges = [[0,1],[1,2],[2,0],[1,3],[3,4]]", output: "[1, 3]",
        starter: "function articulationPoints(n, edges) {\n  // your code here\n}\n\nconsole.log(articulationPoints(5, [[0,1],[1,2],[2,0],[1,3],[3,4]]));" },
      { id: "29-3", title: "Bridges in Graph",
        prompt: "Return all bridges (critical edges) in an undirected graph.",
        input: "n = 5, edges = [[0,1],[1,2],[2,0],[1,3],[3,4]]", output: "[[1,3],[3,4]]",
        starter: "function findBridges(n, edges) {\n  // your code here\n}\n\nconsole.log(findBridges(5, [[0,1],[1,2],[2,0],[1,3],[3,4]]));" },
    ],
  },
  {
    id: 30, name: "Advanced Topics & Problem Solving", tier: "Mastery", difficulty: "Expert / Top-Tier",
    problems: [
      { id: "30-1", title: "Segment Tree (Range Sum + Update)",
        prompt: "Build a segment tree supporting range-sum query and point update.",
        input: "nums=[1,3,5]; query(0,2); update(1,2); query(0,2)", output: "9, 8",
        starter: "class SegmentTree {\n  constructor(nums) {\n    // your code here\n  }\n  update(i, val) {}\n  query(l, r) {}\n}\n\nconst st = new SegmentTree([1,3,5]);\nconsole.log(st.query(0,2));\nst.update(1,2);\nconsole.log(st.query(0,2));" },
      { id: "30-2", title: "Fenwick Tree (BIT)",
        prompt: "Implement a Binary Indexed Tree supporting prefix-sum query and update.",
        input: "nums=[1,2,3,4]; query(2); update(1,+5); query(2)", output: "6, 11",
        starter: "class FenwickTree {\n  constructor(n) {\n    // your code here\n  }\n  update(i, delta) {}\n  query(i) {}\n}\n\nconst bit = new FenwickTree(4);\n[1,2,3,4].forEach((v,i) => bit.update(i+1, v));\nconsole.log(bit.query(2));" },
      { id: "30-3", title: "Meet in the Middle",
        prompt: "Count subsets whose sum equals target using meet-in-the-middle.",
        input: "nums = [1,2,3,4], target = 5", output: "2  ([1,4],[2,3])",
        starter: "function countSubsetsWithSum(nums, target) {\n  // your code here\n}\n\nconsole.log(countSubsetsWithSum([1,2,3,4], 5));" },
    ],
  },
];
